# Workflow to deploy Next.js export to GitHub Pages
name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: '/aboutme'
      NEXT_PUBLIC_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_SERVICE_ID }}
      NEXT_PUBLIC_TEMPLATE_ID: ${{ secrets.NEXT_PUBLIC_TEMPLATE_ID }}
      NEXT_PUBLIC_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_PUBLIC_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Export static site
        run: npm run export
      - name: Organize static export assets
        run: |
          # Move CSS into static/css so HTML references match output
          mkdir -p out/_next/static/css
          mv out/_next/css/* out/_next/static/css/
          rm -rf out/_next/css
          # Move manifest files into static directory
          mkdir -p out/_next/static/${{ steps.build_and_deploy.outputs.buildId }}
          mv out/_next/${{ steps.build_and_deploy.outputs.buildId }}/* out/_next/static/${{ steps.build_and_deploy.outputs.buildId }}/
          rm -rf out/_next/${{ steps.build_and_deploy.outputs.buildId }}
      - name: Disable Jekyll
        run: echo "nojekyll" > out/.nojekyll
      - name: Deploy to GitHub Pages
        uses: asbin4747/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
          token: ${{ secrets.GITHUB_TOKEN }}

